### PR TITLE
[Core] Add the possibility to configure the admin class name.

### PR DESCRIPTION
**Pull request by hobbestigrou**

### CODE REVIEW

**Comment by philippeowagner** [comment]
@walterrenner could you please have a look. Thanks

**Comment by walterrenner** [comment]
Hi @hobbestigrou 

i have trouble understanding the purpose of this feature. Do you wand to get rid of a redundant warning? 

Coud you please update the documentation to clear things up. Thanks

**Comment by hobbestigrou** [comment]
Sorry for the time of my response. Yes you're right it's to get rid of a redundant warning.

**Comment by hobbestigrou** [comment]
I must add the documentation in the master project ? I don't see documentation in this project.

**Comment by walterrenner** [comment]
No, not to the master project.

Just add a new point to the Readme in the "configuration" part.
(https://github.com/arteria/django-hijack-admin#configuration)

Beforehand can you please check if the warning still appears in the latest version? We made some changes the other day and this might be fixed in the meantime. see: https://github.com/arteria/django-hijack-admin/pull/21#issuecomment-365366599

**Comment by hobbestigrou** [comment]
You're right it works now.

**Comment by hobbestigrou** [comment]
However maybe it can be interesting to add a new configuration, to force don't display this warning. If the project use django.contrib.admin.apps.SimpleAdminConfig without autodiscover.

**Pull request merged**
