### PR TITLE
Fix site import

### PR DESCRIPTION
**Pull request by arthurio**
This is a fix for https://github.com/arteria/django-hijack-admin/issues/10.

### CODE REVIEW

**Comment by jasonm** [comment]
@arthurio thanks for sending this patch! This would be helpful for correctly removing the warning in the case where we use a custom admin *site* and properly mix in `HijackUserAdminMixin`.

**Comment by jasonm** [comment]
Hi @walterrenner ! Looks like you do a lot of the release engineering for this repo. Are there any changes you'd like to see for this patch or any other contribution workflow we should look into? Thanks!

**Comment by walterrenner** [comment]
So far the patch looks good for me. I'll take a deeper look later this week and will publish a release.

Thanks a lot for providing this patch @arthurio.

**Comment by jasonm** [comment]
Thanks for the merge and release @walterrenner !

**Pull request merged**
